version: 0.0
os: linux
files:
  - source: /target/test_springboot.jar
#  上传文件夹位置
    destination: /spring_boot_demo
  - source: /scripts/start_server
    destination: /spring_boot_demo

hooks:
  ApplicationStop:
    - location: scripts/stop_server
#    超时时间
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300